spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: "jdbc:postgresql://localhost:5432/jpasample"
#    username: postgres
#    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    name: bigZ
    username: su
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bigZ